In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/raw/nba_pbp/pbp2025.csv")

In [4]:
df.head()

,gameid,period,clock,h_pts,a_pts,team,playerid,player,type,subtype,result,x,y,dist,desc
0,52400111,1,PT12M00.00S,0.0,0.0,NaN,0,NaN,period,start,NaN,0,0,0,Start of 1st Period (7:44 PM EST)
1,52400111,1,PT12M00.00S,NaN,NaN,CHI,202696,N. Vučević,Jump Ball,NaN,NaN,0,0,0,Jump Ball Vucevic vs. Ware: Tip to Adebayo
2,52400111,1,PT11M45.00S,NaN,NaN,MIA,203952,A. Wiggins,Missed Shot,Driving Layup Shot,Missed,-5,29,3,MISS Wiggins 3' Driving Layup
3,52400111,1,PT11M45.00S,NaN,NaN,CHI,1630581,J. Giddey,NaN,NaN,NaN,0,0,0,Giddey BLOCK (1 BLK)
4,52400111,1,PT11M45.00S,NaN,NaN,NaN,1610612748,NaN,Rebound,Unknown,NaN,0,0,0,Heat Rebound

In [5]:
print(df.shape)
print(df.columns)

(651322, 15)
Index(['gameid', 'period', 'clock', 'h_pts', 'a_pts', 'team', 'playerid',
       'player', 'type', 'subtype', 'result', 'x', 'y', 'dist', 'desc'],
      dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 651322 entries, 0 to 651321
Data columns (total 15 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   gameid    651322 non-null  int64
 1   period    651322 non-null  int64
 2   clock     651322 non-null  str
 3   h_pts     168344 non-null  float64
 4   a_pts     168344 non-null  float64
 5   team      597965 non-null  str
 6   playerid  651322 non-null  int64
 7   player    599187 non-null  str
 8   type      616816 non-null  str
 9   subtype   550056 non-null  str
 10  result    234973 non-null  str
 11  x         651322 non-null  int64
 12  y         651322 non-null  int64
 13  dist      651322 non-null  int64
 14  desc      651322 non-null  str
dtypes: float64(2), int64(6), str(7)
memory usage: 74.5 MB

In [7]:
game_id = df["gameid"].iloc[0]
print(game_id)

52400111

In [8]:
game_df = df[df["gameid"] == game_id].copy()

In [9]:
game_df.head(15)

,gameid,period,clock,h_pts,a_pts,team,playerid,player,type,subtype,result,x,y,dist,desc
0,52400111,1,PT12M00.00S,0.0,0.0,NaN,0,NaN,period,start,NaN,0,0,0,Start of 1st Period (7:44 PM EST)
1,52400111,1,PT12M00.00S,NaN,NaN,CHI,202696,N. Vučević,Jump Ball,NaN,NaN,0,0,0,Jump Ball Vucevic vs. Ware: Tip to Adebayo
2,52400111,1,PT11M45.00S,NaN,NaN,MIA,203952,A. Wiggins,Missed Shot,Driving Layup Shot,Missed,-5,29,3,MISS Wiggins 3' Driving Layup
3,52400111,1,PT11M45.00S,NaN,NaN,CHI,1630581,J. Giddey,NaN,NaN,NaN,0,0,0,Giddey BLOCK (1 BLK)
4,52400111,1,PT11M45.00S,NaN,NaN,NaN,1610612748,NaN,Rebound,Unknown,NaN,0,0,0,Heat Rebound
5,52400111,1,PT11M36.00S,0.0,2.0,MIA,1629639,T. Herro,Made Shot,Driving Finger Roll Layup Shot,Made,1,16,2,Herro 2' Driving Finger Roll Layup (2 PTS)
6,52400111,1,PT11M36.00S,NaN,NaN,CHI,1641824,M. Buzelis,Violation,Defensive Goaltending,NaN,0,0,0,Buzelis Violation:Defensive Goaltending (Z.Zarba)
7,52400111,1,PT11M12.00S,NaN,NaN,CHI,1628989,K. Huerter,Missed Shot,Jump Shot,Missed,-129,220,26,MISS Huerter 26' 3PT Jump Shot
8,52400111,1,PT11M08.00S,NaN,NaN,MIA,203952,A. Wiggins,Rebound,Unknown,NaN,0,0,0,Wiggins REBOUND (Off:0 Def:1)
9,52400111,1,PT11M02.00S,0.0,4.0,MIA,202692,A. Burks,Made Shot,Driving Floating Jump Shot,Made,9,84,8,Burks 8' Driving Floating Jump Shot (2 PTS) (A...
10,52400111,1,PT10M49.00S,2.0,4.0,CHI,1629632,C. White,Made Shot,Driving Reverse Layup Shot,Made,-4,-2,0,White Driving Reverse Layup (2 PTS)
11,52400111,1,PT10M49.00S,NaN,NaN,MIA,1642276,K. Ware,Foul,Shooting,NaN,0,0,0,Ware S.FOUL (P1.T1) (J.Van Duyne)
12,52400111,1,PT10M49.00S,3.0,4.0,CHI,1629632,C. White,Free Throw,Free Throw 1 of 1,NaN,0,0,0,White Free Throw 1 of 1 (3 PTS)
13,52400111,1,PT10M38.00S,3.0,6.0,MIA,1629639,T. Herro,Made Shot,Driving Reverse Layup Shot,Made,13,11,2,Herro 2' Driving Reverse Layup (4 PTS)
14,52400111,1,PT10M27.00S,NaN,NaN,CHI,1630581,J. Giddey,Missed Shot,Driving Floating Jump Shot,Missed,-38,59,7,MISS Giddey 7' Driving Floating Jump Shot

In [10]:
game_df.tail(15)

,gameid,period,clock,h_pts,a_pts,team,playerid,player,type,subtype,result,x,y,dist,desc
464,52400111,4,PT01M23.00S,NaN,NaN,MIA,1628389,B. Adebayo,Substitution,NaN,NaN,0,0,0,SUB: Johnson FOR Adebayo
465,52400111,4,PT01M23.00S,NaN,NaN,MIA,1629639,T. Herro,Substitution,NaN,NaN,0,0,0,SUB: Robinson FOR Herro
466,52400111,4,PT01M23.00S,NaN,NaN,MIA,203952,A. Wiggins,Substitution,NaN,NaN,0,0,0,SUB: Jaquez Jr. FOR Wiggins
467,52400111,4,PT01M23.00S,NaN,NaN,MIA,1630558,D. Mitchell,Substitution,NaN,NaN,0,0,0,SUB: Highsmith FOR Mitchell
468,52400111,4,PT01M23.00S,NaN,NaN,MIA,203937,K. Anderson,Free Throw,Free Throw 2 of 2,NaN,0,0,0,MISS Anderson Free Throw 2 of 2
469,52400111,4,PT01M21.00S,NaN,NaN,CHI,1629659,T. Horton-Tucker,Rebound,Unknown,NaN,0,0,0,Horton-Tucker REBOUND (Off:0 Def:1)
470,52400111,4,PT01M15.00S,88.0,109.0,CHI,1629659,T. Horton-Tucker,Made Shot,Driving Finger Roll Layup Shot,Made,-11,15,2,Horton-Tucker 2' Driving Finger Roll Layup (7 ...
471,52400111,4,PT00M57.90S,NaN,NaN,MIA,1642352,K. Johnson,Turnover,Out of Bounds - Bad Pass Turnover,NaN,0,0,0,Johnson Out of Bounds - Bad Pass Turnover Turn...
472,52400111,4,PT00M49.00S,90.0,109.0,CHI,1629659,T. Horton-Tucker,Made Shot,Driving Finger Roll Layup Shot,Made,0,27,3,Horton-Tucker 3' Driving Finger Roll Layup (9 ...
473,52400111,4,PT00M28.50S,NaN,NaN,MIA,1631170,J. Jaquez Jr.,Missed Shot,Step Back Jump shot,Missed,-93,225,24,MISS Jaquez Jr. 24' 3PT Step Back Jump Shot
474,52400111,4,PT00M27.00S,NaN,NaN,NaN,1610612741,NaN,Rebound,Unknown,NaN,0,0,0,BULLS Rebound
475,52400111,4,PT00M21.10S,NaN,NaN,MIA,203937,K. Anderson,Foul,Personal,NaN,0,0,0,Anderson P.FOUL (P1.T1) (Z.Zarba)
476,52400111,4,PT00M17.40S,NaN,NaN,CHI,1629659,T. Horton-Tucker,Missed Shot,Jump Shot,Missed,99,244,26,MISS Horton-Tucker 26' 3PT Jump Shot
477,52400111,4,PT00M15.50S,NaN,NaN,MIA,1629312,H. Highsmith,Rebound,Unknown,NaN,0,0,0,Highsmith REBOUND (Off:0 Def:1)
478,52400111,4,PT00M00.00S,90.0,109.0,NaN,0,NaN,period,end,NaN,0,0,0,End of 4th Period (10:00 PM EST)

In [11]:
df["h_pts"] = df.groupby("gameid")["h_pts"].ffill().fillna(0)
df["a_pts"] = df.groupby("gameid")["a_pts"].ffill().fillna(0)

In [12]:
game_df = df[df["gameid"] == game_id]

game_df.head(15)

,gameid,period,clock,h_pts,a_pts,team,playerid,player,type,subtype,result,x,y,dist,desc
0,52400111,1,PT12M00.00S,0.0,0.0,NaN,0,NaN,period,start,NaN,0,0,0,Start of 1st Period (7:44 PM EST)
1,52400111,1,PT12M00.00S,0.0,0.0,CHI,202696,N. Vučević,Jump Ball,NaN,NaN,0,0,0,Jump Ball Vucevic vs. Ware: Tip to Adebayo
2,52400111,1,PT11M45.00S,0.0,0.0,MIA,203952,A. Wiggins,Missed Shot,Driving Layup Shot,Missed,-5,29,3,MISS Wiggins 3' Driving Layup
3,52400111,1,PT11M45.00S,0.0,0.0,CHI,1630581,J. Giddey,NaN,NaN,NaN,0,0,0,Giddey BLOCK (1 BLK)
4,52400111,1,PT11M45.00S,0.0,0.0,NaN,1610612748,NaN,Rebound,Unknown,NaN,0,0,0,Heat Rebound
5,52400111,1,PT11M36.00S,0.0,2.0,MIA,1629639,T. Herro,Made Shot,Driving Finger Roll Layup Shot,Made,1,16,2,Herro 2' Driving Finger Roll Layup (2 PTS)
6,52400111,1,PT11M36.00S,0.0,2.0,CHI,1641824,M. Buzelis,Violation,Defensive Goaltending,NaN,0,0,0,Buzelis Violation:Defensive Goaltending (Z.Zarba)
7,52400111,1,PT11M12.00S,0.0,2.0,CHI,1628989,K. Huerter,Missed Shot,Jump Shot,Missed,-129,220,26,MISS Huerter 26' 3PT Jump Shot
8,52400111,1,PT11M08.00S,0.0,2.0,MIA,203952,A. Wiggins,Rebound,Unknown,NaN,0,0,0,Wiggins REBOUND (Off:0 Def:1)
9,52400111,1,PT11M02.00S,0.0,4.0,MIA,202692,A. Burks,Made Shot,Driving Floating Jump Shot,Made,9,84,8,Burks 8' Driving Floating Jump Shot (2 PTS) (A...
10,52400111,1,PT10M49.00S,2.0,4.0,CHI,1629632,C. White,Made Shot,Driving Reverse Layup Shot,Made,-4,-2,0,White Driving Reverse Layup (2 PTS)
11,52400111,1,PT10M49.00S,2.0,4.0,MIA,1642276,K. Ware,Foul,Shooting,NaN,0,0,0,Ware S.FOUL (P1.T1) (J.Van Duyne)
12,52400111,1,PT10M49.00S,3.0,4.0,CHI,1629632,C. White,Free Throw,Free Throw 1 of 1,NaN,0,0,0,White Free Throw 1 of 1 (3 PTS)
13,52400111,1,PT10M38.00S,3.0,6.0,MIA,1629639,T. Herro,Made Shot,Driving Reverse Layup Shot,Made,13,11,2,Herro 2' Driving Reverse Layup (4 PTS)
14,52400111,1,PT10M27.00S,3.0,6.0,CHI,1630581,J. Giddey,Missed Shot,Driving Floating Jump Shot,Missed,-38,59,7,MISS Giddey 7' Driving Floating Jump Shot

In [13]:
game_df.tail(10)[["period", "clock", "h_pts", "a_pts", "desc"]]

,period,clock,h_pts,a_pts,desc
469,4,PT01M21.00S,86.0,109.0,Horton-Tucker REBOUND (Off:0 Def:1)
470,4,PT01M15.00S,88.0,109.0,Horton-Tucker 2' Driving Finger Roll Layup (7 ...
471,4,PT00M57.90S,88.0,109.0,Johnson Out of Bounds - Bad Pass Turnover Turn...
472,4,PT00M49.00S,90.0,109.0,Horton-Tucker 3' Driving Finger Roll Layup (9 ...
473,4,PT00M28.50S,90.0,109.0,MISS Jaquez Jr. 24' 3PT Step Back Jump Shot
474,4,PT00M27.00S,90.0,109.0,BULLS Rebound
475,4,PT00M21.10S,90.0,109.0,Anderson P.FOUL (P1.T1) (Z.Zarba)
476,4,PT00M17.40S,90.0,109.0,MISS Horton-Tucker 26' 3PT Jump Shot
477,4,PT00M15.50S,90.0,109.0,Highsmith REBOUND (Off:0 Def:1)
478,4,PT00M00.00S,90.0,109.0,End of 4th Period (10:00 PM EST)

In [14]:
df["score_diff"] = df["h_pts"] - df["a_pts"]

In [15]:
def convert_clock(clock):
    clock = clock.replace("PT", "")
    
    minutes = clock.split("M")[0]
    seconds = clock.split("M")[1].replace("S","")
    
    return int(minutes) + float(seconds)/60


df["time_remaining"] = df["clock"].apply(convert_clock)

In [16]:
df[[
    "clock",
    "time_remaining",
    "score_diff"
]].head(20)

          clock  time_remaining  score_diff
0   PT12M00.00S       12.000000         0.0
1   PT12M00.00S       12.000000         0.0
2   PT11M45.00S       11.750000         0.0
3   PT11M45.00S       11.750000         0.0
4   PT11M45.00S       11.750000         0.0
5   PT11M36.00S       11.600000        -2.0
6   PT11M36.00S       11.600000        -2.0
7   PT11M12.00S       11.200000        -2.0
8   PT11M08.00S       11.133333        -2.0
9   PT11M02.00S       11.033333        -4.0
10  PT10M49.00S       10.816667        -2.0
11  PT10M49.00S       10.816667        -2.0
12  PT10M49.00S       10.816667        -1.0
13  PT10M38.00S       10.633333        -3.0
14  PT10M27.00S       10.450000        -3.0
15  PT10M25.00S       10.416667        -3.0
16  PT10M23.00S       10.383333        -1.0
17  PT10M13.00S       10.216667        -3.0
18  PT10M01.00S       10.016667        -3.0
19  PT09M59.00S        9.983333        -3.0

In [17]:
final_scores = df.groupby("gameid").tail(1)[["gameid", "h_pts", "a_pts"]].copy()

In [18]:
final_scores["home_win"] = (final_scores["h_pts"] > final_scores["a_pts"]).astype(int)
final_scores.head()

        gameid  h_pts  a_pts  home_win
478   52400111   90.0  109.0         0
1012  52400121  121.0  116.0         1
1485  52400131  106.0  120.0         0
1990  52400201  114.0  123.0         0
2499  52400211  120.0  106.0         1

In [19]:
df = df.merge(final_scores[["gameid", "home_win"]], on="gameid", how="left")

In [20]:
ml_df = df[[
    "score_diff",
    "time_remaining",
    "period",
    "home_win"
]].dropna()

In [21]:
ml_df.head()

   score_diff  time_remaining  period  home_win
0         0.0           12.00       1         0
1         0.0           12.00       1         0
2         0.0           11.75       1         0
3         0.0           11.75       1         0
4         0.0           11.75       1         0

In [22]:
ml_df["home_win"].value_counts()

home_win
1    354592
0    296730
Name: count, dtype: int64

In [24]:
import torch

x = ml_df[["score_diff", "time_remaining", "period"]].values
y = ml_df["home_win"].values

In [25]:
x = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.float32).view(-1, 1)

In [27]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

In [30]:
import torch

x_train = torch.tensor(x_train, dtype=torch.float32)
x_test = torch.tensor(x_test, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.float32).view(-1, 1)
y_test = torch.tensor(y_test, dtype=torch.float32).view(-1, 1)

C:\Users\fanta\AppData\Local\Temp\ipykernel_39384\4243471127.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x_train = torch.tensor(x_train, dtype=torch.float32)
C:\Users\fanta\AppData\Local\Temp\ipykernel_39384\4243471127.py:4: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x_test = torch.tensor(x_test, dtype=torch.float32)
C:\Users\fanta\AppData\Local\Temp\ipykernel_39384\4243471127.py:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_train = torch.tensor(y_train, dtype=torch.float32).view(-1, 1)
C:\Users\fanta\AppData\Local\Temp\ipykernel_39384\4243471127.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test = torch.tensor(y_test, dtype=torch.float32).view(-1, 1)

In [31]:
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

x_train = x_train.to(device)
x_test = x_test.to(device)
y_train = y_train.to(device)
y_test = y_test.to(device)

In [32]:
import torch.nn as nn

class WinModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(3, 32),
            nn.ReLU(),
            nn.Linear(32, 16),
            nn.ReLU(),
            nn.Linear(16, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.net(x)

model = WinModel().to(device)

In [33]:
import torch.optim as optim

criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [35]:
epochs = 10

for epoch in range(epochs):
    model.train()

    # Forward pass
    outputs = model(x_train)
    loss = criterion(outputs, y_train)

    # Backprop
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # Evaluate accuracy on train set
    with torch.no_grad():
        preds = (outputs > 0.5).float()
        acc = (preds == y_train).float().mean()

    print(f"Epoch {epoch+1}/{epochs}, Loss: {loss.item():.4f}, Accuracy: {acc.item():.4f}")

Epoch 1/10, Loss: 0.7415, Accuracy: 0.4559
Epoch 2/10, Loss: 0.7239, Accuracy: 0.4559
Epoch 3/10, Loss: 0.7072, Accuracy: 0.4559
Epoch 4/10, Loss: 0.6915, Accuracy: 0.4559
Epoch 5/10, Loss: 0.6767, Accuracy: 0.4559
Epoch 6/10, Loss: 0.6627, Accuracy: 0.4559
Epoch 7/10, Loss: 0.6494, Accuracy: 0.4559
Epoch 8/10, Loss: 0.6369, Accuracy: 0.5203
Epoch 9/10, Loss: 0.6250, Accuracy: 0.6358
Epoch 10/10, Loss: 0.6139, Accuracy: 0.6887

In [37]:
model.eval()

with torch.no_grad():
    test_outputs = model(x_test)
    test_preds = (test_outputs > 0.5).float()
    test_acc = (test_preds == y_test).float().mean()

print("Test Accuracy:", test_acc.item())

Test Accuracy: 0.7077035307884216