# Advanced Feature Engineering

The first version of the NBA win probability model was able to predict outcomes using basic game-state features such as score differential, time remaining, and momentum.

While the model achieved strong baseline performance, most of its predictive power came from the current score differential. This suggests that additional basketball-specific features are needed to better represent the state of a live game.

This notebook focuses on extracting advanced features from play-by-play data to improve the model's understanding of game context.

The features introduced in this stage aim to represent:

- Which team currently has possession
- Recent scoring trends
- Late-game situations
- Strategic advantages that are not represented by the score alone

In [1]:
import pandas as pd
import numpy as np

df = pd.read_parquet("../data/processed/ml_dataset_sample.parquet")

print(df.shape)
df.head()

(2000000, 8)

,gameid,season,period,game_seconds_remaining,score_diff,score_diff_squared,momentum,home_win
0,22300188,2024,3,1255.0,0.0,0.0,-0.35,1
1,20300391,2004,1,2523.0,0.0,0.0,0.00,1
2,20301094,2004,1,2277.0,-5.0,25.0,-0.25,1
3,29600303,1997,2,1609.0,0.0,0.0,0.00,0
4,22000011,2021,4,356.0,14.0,196.0,-0.20,1

In [2]:
import pandas as pd

full_df = pd.read_parquet("../data/processed/ml_dataset.parquet")
sample_df = pd.read_parquet("../data/processed/ml_dataset_sample.parquet")

print("Full dataset:")
print(full_df.shape)
print(full_df.columns.tolist())

print("\nSample dataset:")
print(sample_df.shape)
print(sample_df.columns.tolist())

Full dataset:
(18255730, 8)
['gameid', 'season', 'period', 'game_seconds_remaining', 'score_diff', 'score_diff_squared', 'momentum', 'home_win']

Sample dataset:
(2000000, 8)
['gameid', 'season', 'period', 'game_seconds_remaining', 'score_diff', 'score_diff_squared', 'momentum', 'home_win']

# Game State Features

This section introduces features that describe the current situation of the game. These features capture high-pressure moments such as close games, late-game scenarios, and situations where a single possession can significantly impact the final outcome.

In [3]:
df["clutch"] = (
    (df["game_seconds_remaining"] <= 300) &
    (abs(df["score_diff"]) <= 5)
).astype(int)

In [4]:
df["final_two_minutes"] = (
    df["game_seconds_remaining"] <= 120
).astype(int)

In [5]:
df["one_possession_game"] = (
    abs(df["score_diff"]) <= 3
).astype(int)

In [6]:
df["is_tied"] = (
    df["score_diff"] == 0
).astype(int)

In [7]:
df["second_half"] = (
    df["period"] >= 3
).astype(int)

In [8]:
df.head()

,gameid,season,period,game_seconds_remaining,score_diff,score_diff_squared,momentum,home_win,clutch,final_two_minutes,one_possession_game,is_tied,second_half
0,22300188,2024,3,1255.0,0.0,0.0,-0.35,1,0,0,1,1,1
1,20300391,2004,1,2523.0,0.0,0.0,0.00,1,0,0,1,1,0
2,20301094,2004,1,2277.0,-5.0,25.0,-0.25,1,0,0,0,0,0
3,29600303,1997,2,1609.0,0.0,0.0,0.00,0,0,0,1,1,0
4,22000011,2021,4,356.0,14.0,196.0,-0.20,1,0,0,0,0,1

In [9]:
df.to_parquet("../data/processed/ml_dataset_features_v1.parquet")

In [10]:
new_features = [
    "clutch",
    "final_two_minutes",
    "one_possession_game",
    "is_tied",
    "second_half"
]

df[new_features].describe()

,clutch,final_two_minutes,one_possession_game,is_tied,second_half
count,2.000000e+06,2.000000e+06,2.000000e+06,2.000000e+06,2.000000e+06
mean,5.858150e-02,3.588750e-02,5.870215e-01,4.383045e-01,5.076490e-01
std,2.348398e-01,1.860097e-01,4.923691e-01,4.961792e-01,4.999416e-01
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00
75%,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
max,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00

In [11]:
df[new_features].sum()

clutch                  117163
final_two_minutes        71775
one_possession_game    1174043
is_tied                 876609
second_half            1015298
dtype: int64

In [12]:
from sklearn.model_selection import train_test_split

df_exp = df.sample(n=1_000_000, random_state=42)

features = [
    "period",
    "game_seconds_remaining",
    "score_diff",
    "score_diff_squared",
    "momentum",
    "clutch",
    "final_two_minutes",
    "one_possession_game",
    "is_tied",
    "second_half"
]

X = df_exp[features]
y = df_exp["home_win"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(X_train.shape)
print(X_test.shape)

(800000, 10)
(200000, 10)

In [13]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=50,
    max_depth=12,
    min_samples_leaf=10,
    random_state=42,
    n_jobs=1
)

rf.fit(X_train, y_train)

RandomForestClassifier(max_depth=12, min_samples_leaf=10, n_estimators=50,
                       n_jobs=1, random_state=42)

In [14]:
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

y_pred = rf.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print()
print(confusion_matrix(y_test, y_pred))
print()
print(classification_report(y_test, y_pred))

Accuracy: 0.70471

[[48910 45730]
 [13328 92032]]

              precision    recall  f1-score   support

           0       0.79      0.52      0.62     94640
           1       0.67      0.87      0.76    105360

    accuracy                           0.70    200000
   macro avg       0.73      0.70      0.69    200000
weighted avg       0.72      0.70      0.69    200000

In [15]:
importance = pd.DataFrame({
    "feature": features,
    "importance": rf.feature_importances_
}).sort_values("importance", ascending=False)

importance

                  feature  importance
2              score_diff    0.608796
4                momentum    0.151441
3      score_diff_squared    0.076845
7     one_possession_game    0.047082
0                  period    0.043918
1  game_seconds_remaining    0.041882
8                 is_tied    0.014566
9             second_half    0.013250
6       final_two_minutes    0.001198
5                  clutch    0.001022

In [16]:
df.to_parquet(
    "../data/processed/ml_dataset_features_v1.parquet",
    index=False
)

# Recent Scoring Features

Recent scoring features measure how much each team has scored over short periods immediately preceding each game state.

Two windows will be tested:

- **2-minute scoring differential**
- **5-minute scoring differential**

These features are intended to capture short-term scoring momentum that may not be fully represented by the current score differential.

In [17]:
import os

print(os.listdir("../data/processed"))

['ml_dataset.parquet', 'ml_dataset_features_v1.parquet', 'ml_dataset_sample.parquet']

In [18]:
import os

for root, dirs, files in os.walk("../"):
    for file in files:
        if file.lower().endswith((".csv", ".parquet")):
            print(os.path.join(root, file))

../data\processed\ml_dataset.parquet
../data\processed\ml_dataset_features_v1.parquet
../data\processed\ml_dataset_sample.parquet
../data\raw\nba_pbp\pbp1997.csv
../data\raw\nba_pbp\pbp1998.csv
../data\raw\nba_pbp\pbp1999.csv
../data\raw\nba_pbp\pbp2000.csv
../data\raw\nba_pbp\pbp2001.csv
../data\raw\nba_pbp\pbp2002.csv
../data\raw\nba_pbp\pbp2003.csv
../data\raw\nba_pbp\pbp2004.csv
../data\raw\nba_pbp\pbp2005.csv
../data\raw\nba_pbp\pbp2006.csv
../data\raw\nba_pbp\pbp2007.csv
../data\raw\nba_pbp\pbp2008.csv
../data\raw\nba_pbp\pbp2009.csv
../data\raw\nba_pbp\pbp2010.csv
../data\raw\nba_pbp\pbp2011.csv
../data\raw\nba_pbp\pbp2012.csv
../data\raw\nba_pbp\pbp2013.csv
../data\raw\nba_pbp\pbp2014.csv
../data\raw\nba_pbp\pbp2015.csv
../data\raw\nba_pbp\pbp2016.csv
../data\raw\nba_pbp\pbp2017.csv
../data\raw\nba_pbp\pbp2018.csv
../data\raw\nba_pbp\pbp2019.csv
../data\raw\nba_pbp\pbp2020.csv
../data\raw\nba_pbp\pbp2021.csv
../data\raw\nba_pbp\pbp2022.csv
../data\raw\nba_pbp\pbp2023.csv
../data\raw\nba_pbp\pbp2024.csv
../data\raw\nba_pbp\pbp2025.csv
../data\raw\nba_pbp\pbp2026.csv
../venv\Lib\site-packages\matplotlib\mpl-data\sample_data\data_x_x2_x3.csv
../venv\Lib\site-packages\matplotlib\mpl-data\sample_data\msft.csv
../venv\Lib\site-packages\matplotlib\mpl-data\sample_data\Stocks.csv
../venv\Lib\site-packages\numpy\random\tests\data\mt19937-testset-1.csv
../venv\Lib\site-packages\numpy\random\tests\data\mt19937-testset-2.csv
../venv\Lib\site-packages\numpy\random\tests\data\pcg64-testset-1.csv
../venv\Lib\site-packages\numpy\random\tests\data\pcg64-testset-2.csv
../venv\Lib\site-packages\numpy\random\tests\data\pcg64dxsm-testset-1.csv
../venv\Lib\site-packages\numpy\random\tests\data\pcg64dxsm-testset-2.csv
../venv\Lib\site-packages\numpy\random\tests\data\philox-testset-1.csv
../venv\Lib\site-packages\numpy\random\tests\data\philox-testset-2.csv
../venv\Lib\site-packages\numpy\random\tests\data\sfc64-testset-1.csv
../venv\Lib\site-packages\numpy\random\tests\data\sfc64-testset-2.csv
../venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arccos.csv
../venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arccosh.csv
../venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arcsin.csv
../venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arcsinh.csv
../venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arctan.csv
../venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arctanh.csv
../venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-cbrt.csv
../venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-cos.csv
../venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-cosh.csv
../venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-exp.csv
../venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-exp2.csv
../venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-expm1.csv
../venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-log.csv
../venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-log10.csv
../venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-log1p.csv
../venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-log2.csv
../venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-sin.csv
../venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-sinh.csv
../venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-tan.csv
../venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-tanh.csv
../venv\Lib\site-packages\pyarrow\tests\data\parquet\v0.7.1.all-named-index.parquet
../venv\Lib\site-packages\pyarrow\tests\data\parquet\v0.7.1.column-metadata-handling.parquet
../venv\Lib\site-packages\pyarrow\tests\data\parquet\v0.7.1.parquet
../venv\Lib\site-packages\pyarrow\tests\data\parquet\v0.7.1.some-named-index.parquet
../venv\Lib\site-packages\scipy\signal\tests\data\GLB.Ts+dSST.csv
../venv\Lib\site-packages\sklearn\datasets\data\breast_cancer.csv
../venv\Lib\site-packages\sklearn\datasets\data\iris.csv
../venv\Lib\site-packages\sklearn\datasets\data\linnerud_exercise.csv
../venv\Lib\site-packages\sklearn\datasets\data\linnerud_physiological.csv
../venv\Lib\site-packages\sklearn\datasets\data\wine_data.csv
../venv\Lib\site-packages\tornado\test\csv_translations\fr_FR.csv

In [19]:
pbp = pd.read_csv("../data/raw/nba_pbp/pbp2025.csv")

print(pbp.shape)
print(pbp.columns.tolist())
pbp.head()

(651322, 15)
['gameid', 'period', 'clock', 'h_pts', 'a_pts', 'team', 'playerid', 'player', 'type', 'subtype', 'result', 'x', 'y', 'dist', 'desc']

,gameid,period,clock,h_pts,a_pts,team,playerid,player,type,subtype,result,x,y,dist,desc
0,52400111,1,PT12M00.00S,0.0,0.0,NaN,0,NaN,period,start,NaN,0,0,0,Start of 1st Period (7:44 PM EST)
1,52400111,1,PT12M00.00S,NaN,NaN,CHI,202696,N. Vučević,Jump Ball,NaN,NaN,0,0,0,Jump Ball Vucevic vs. Ware: Tip to Adebayo
2,52400111,1,PT11M45.00S,NaN,NaN,MIA,203952,A. Wiggins,Missed Shot,Driving Layup Shot,Missed,-5,29,3,MISS Wiggins 3' Driving Layup
3,52400111,1,PT11M45.00S,NaN,NaN,CHI,1630581,J. Giddey,NaN,NaN,NaN,0,0,0,Giddey BLOCK (1 BLK)
4,52400111,1,PT11M45.00S,NaN,NaN,NaN,1610612748,NaN,Rebound,Unknown,NaN,0,0,0,Heat Rebound

In [20]:
pbp["type"].value_counts()

type
Rebound           138062
Missed Shot       125371
Made Shot         109602
Substitution       64482
Free Throw         57568
Foul               50713
Turnover           37696
Timeout            14749
period             10700
Instant Replay      3165
Jump Ball           2372
Violation           2242
Ejection              94
Name: count, dtype: int64

In [21]:
pbp[pbp["type"].isin(["Made Shot", "Free Throw"])][
    ["gameid", "period", "clock", "team", "type", "subtype", "desc"]
].head(30)

,gameid,period,clock,team,type,subtype,desc
5,52400111,1,PT11M36.00S,MIA,Made Shot,Driving Finger Roll Layup Shot,Herro 2' Driving Finger Roll Layup (2 PTS)
9,52400111,1,PT11M02.00S,MIA,Made Shot,Driving Floating Jump Shot,Burks 8' Driving Floating Jump Shot (2 PTS) (A...
10,52400111,1,PT10M49.00S,CHI,Made Shot,Driving Reverse Layup Shot,White Driving Reverse Layup (2 PTS)
12,52400111,1,PT10M49.00S,CHI,Free Throw,Free Throw 1 of 1,White Free Throw 1 of 1 (3 PTS)
13,52400111,1,PT10M38.00S,MIA,Made Shot,Driving Reverse Layup Shot,Herro 2' Driving Reverse Layup (4 PTS)
16,52400111,1,PT10M23.00S,CHI,Made Shot,Putback Layup Shot,Giddey 2' Putback Layup (2 PTS)
17,52400111,1,PT10M13.00S,MIA,Made Shot,Cutting Dunk Shot,Adebayo 1' Cutting Dunk Shot (2 PTS) (Herro 1 ...
20,52400111,1,PT09M48.00S,MIA,Made Shot,Driving Layup Shot,Herro 2' Driving Layup (6 PTS) (Wiggins 1 AST)
28,52400111,1,PT09M09.00S,MIA,Made Shot,Running Jump Shot,Wiggins 25' 3PT Running Jump Shot (3 PTS) (Bur...
31,52400111,1,PT08M23.00S,MIA,Made Shot,Driving Finger Roll Layup Shot,Herro 2' Driving Finger Roll Layup (8 PTS)
32,52400111,1,PT08M18.00S,CHI,Made Shot,Pullup Jump shot,White 28' 3PT Pullup Jump Shot (6 PTS)
33,52400111,1,PT07M59.00S,MIA,Made Shot,Cutting Layup Shot,Wiggins 3' Cutting Layup Shot (5 PTS) (Adebayo...
35,52400111,1,PT07M55.00S,CHI,Free Throw,Free Throw 1 of 2,Giddey Free Throw 1 of 2 (3 PTS)
36,52400111,1,PT07M55.00S,CHI,Free Throw,Free Throw 2 of 2,Giddey Free Throw 2 of 2 (4 PTS)
38,52400111,1,PT07M36.00S,MIA,Made Shot,Cutting Dunk Shot,Wiggins 2' Cutting Dunk Shot (7 PTS) (Ware 1 AST)
54,52400111,1,PT06M13.00S,CHI,Made Shot,Driving Finger Roll Layup Shot,Vucevic 6' Driving Finger Roll Layup (2 PTS) (...
55,52400111,1,PT05M50.00S,MIA,Made Shot,Step Back Jump shot,Herro 28' 3PT Step Back Jump Shot (11 PTS)
58,52400111,1,PT05M35.00S,MIA,Made Shot,Running Jump Shot,Highsmith 3PT Running Jump Shot (3 PTS) (Herro...
68,52400111,1,PT04M56.00S,CHI,Made Shot,Running Layup Shot,Giddey 1' Running Layup (6 PTS)
69,52400111,1,PT04M42.00S,MIA,Made Shot,Jump Shot,Wiggins 26' 3PT Jump Shot (10 PTS) (Mitchell 1...
70,52400111,1,PT04M29.00S,CHI,Made Shot,Driving Layup Shot,Terry 1' Driving Layup (2 PTS)
73,52400111,1,PT04M09.00S,CHI,Made Shot,Cutting Layup Shot,Giddey 2' Cutting Layup Shot (8 PTS) (White 1 ...
80,52400111,1,PT03M35.00S,MIA,Made Shot,Jump Shot,Adebayo 27' 3PT Jump Shot (5 PTS) (Anderson 1 ...
93,52400111,1,PT02M04.00S,MIA,Free Throw,Free Throw 1 of 2,Adebayo Free Throw 1 of 2 (6 PTS)
97,52400111,1,PT02M04.00S,MIA,Free Throw,Free Throw 2 of 2,Adebayo Free Throw 2 of 2 (7 PTS)
98,52400111,1,PT01M55.00S,CHI,Made Shot,Pullup Jump shot,Giddey 25' 3PT Pullup Jump Shot (11 PTS)
99,52400111,1,PT01M35.00S,MIA,Made Shot,Step Back Jump shot,Herro 28' 3PT Step Back Jump Shot (14 PTS) (An...
103,52400111,1,PT01M01.00S,MIA,Free Throw,Free Throw 1 of 2,Herro Free Throw 1 of 2 (15 PTS)
104,52400111,1,PT01M01.00S,MIA,Free Throw,Free Throw 2 of 2,Herro Free Throw 2 of 2 (16 PTS)
105,52400111,1,PT00M49.60S,CHI,Made Shot,Jump Shot,Collins 21' Jump Shot (2 PTS) (Giddey 1 AST)

In [22]:
scoring_check = pbp[pbp["type"].isin(["Made Shot", "Free Throw"])][
    ["gameid", "period", "clock", "team", "type", "h_pts", "a_pts", "desc"]
].head(30)

scoring_check

,gameid,period,clock,team,type,h_pts,a_pts,desc
5,52400111,1,PT11M36.00S,MIA,Made Shot,0.0,2.0,Herro 2' Driving Finger Roll Layup (2 PTS)
9,52400111,1,PT11M02.00S,MIA,Made Shot,0.0,4.0,Burks 8' Driving Floating Jump Shot (2 PTS) (A...
10,52400111,1,PT10M49.00S,CHI,Made Shot,2.0,4.0,White Driving Reverse Layup (2 PTS)
12,52400111,1,PT10M49.00S,CHI,Free Throw,3.0,4.0,White Free Throw 1 of 1 (3 PTS)
13,52400111,1,PT10M38.00S,MIA,Made Shot,3.0,6.0,Herro 2' Driving Reverse Layup (4 PTS)
16,52400111,1,PT10M23.00S,CHI,Made Shot,5.0,6.0,Giddey 2' Putback Layup (2 PTS)
17,52400111,1,PT10M13.00S,MIA,Made Shot,5.0,8.0,Adebayo 1' Cutting Dunk Shot (2 PTS) (Herro 1 ...
20,52400111,1,PT09M48.00S,MIA,Made Shot,5.0,10.0,Herro 2' Driving Layup (6 PTS) (Wiggins 1 AST)
28,52400111,1,PT09M09.00S,MIA,Made Shot,5.0,13.0,Wiggins 25' 3PT Running Jump Shot (3 PTS) (Bur...
31,52400111,1,PT08M23.00S,MIA,Made Shot,5.0,15.0,Herro 2' Driving Finger Roll Layup (8 PTS)
32,52400111,1,PT08M18.00S,CHI,Made Shot,8.0,15.0,White 28' 3PT Pullup Jump Shot (6 PTS)
33,52400111,1,PT07M59.00S,MIA,Made Shot,8.0,17.0,Wiggins 3' Cutting Layup Shot (5 PTS) (Adebayo...
35,52400111,1,PT07M55.00S,CHI,Free Throw,9.0,17.0,Giddey Free Throw 1 of 2 (3 PTS)
36,52400111,1,PT07M55.00S,CHI,Free Throw,10.0,17.0,Giddey Free Throw 2 of 2 (4 PTS)
38,52400111,1,PT07M36.00S,MIA,Made Shot,10.0,19.0,Wiggins 2' Cutting Dunk Shot (7 PTS) (Ware 1 AST)
54,52400111,1,PT06M13.00S,CHI,Made Shot,12.0,19.0,Vucevic 6' Driving Finger Roll Layup (2 PTS) (...
55,52400111,1,PT05M50.00S,MIA,Made Shot,12.0,22.0,Herro 28' 3PT Step Back Jump Shot (11 PTS)
58,52400111,1,PT05M35.00S,MIA,Made Shot,12.0,25.0,Highsmith 3PT Running Jump Shot (3 PTS) (Herro...
68,52400111,1,PT04M56.00S,CHI,Made Shot,14.0,25.0,Giddey 1' Running Layup (6 PTS)
69,52400111,1,PT04M42.00S,MIA,Made Shot,14.0,28.0,Wiggins 26' 3PT Jump Shot (10 PTS) (Mitchell 1...
70,52400111,1,PT04M29.00S,CHI,Made Shot,16.0,28.0,Terry 1' Driving Layup (2 PTS)
73,52400111,1,PT04M09.00S,CHI,Made Shot,18.0,28.0,Giddey 2' Cutting Layup Shot (8 PTS) (White 1 ...
80,52400111,1,PT03M35.00S,MIA,Made Shot,18.0,31.0,Adebayo 27' 3PT Jump Shot (5 PTS) (Anderson 1 ...
93,52400111,1,PT02M04.00S,MIA,Free Throw,18.0,32.0,Adebayo Free Throw 1 of 2 (6 PTS)
97,52400111,1,PT02M04.00S,MIA,Free Throw,18.0,33.0,Adebayo Free Throw 2 of 2 (7 PTS)
98,52400111,1,PT01M55.00S,CHI,Made Shot,21.0,33.0,Giddey 25' 3PT Pullup Jump Shot (11 PTS)
99,52400111,1,PT01M35.00S,MIA,Made Shot,21.0,36.0,Herro 28' 3PT Step Back Jump Shot (14 PTS) (An...
103,52400111,1,PT01M01.00S,MIA,Free Throw,21.0,37.0,Herro Free Throw 1 of 2 (15 PTS)
104,52400111,1,PT01M01.00S,MIA,Free Throw,21.0,38.0,Herro Free Throw 2 of 2 (16 PTS)
105,52400111,1,PT00M49.60S,CHI,Made Shot,23.0,38.0,Collins 21' Jump Shot (2 PTS) (Giddey 1 AST)

In [23]:
print(
    pbp[pbp["type"].isin(["Made Shot", "Free Throw"])][
        ["h_pts", "a_pts"]
    ].head(30).to_string(index=False)
)

 h_pts  a_pts
   0.0    2.0
   0.0    4.0
   2.0    4.0
   3.0    4.0
   3.0    6.0
   5.0    6.0
   5.0    8.0
   5.0   10.0
   5.0   13.0
   5.0   15.0
   8.0   15.0
   8.0   17.0
   9.0   17.0
  10.0   17.0
  10.0   19.0
  12.0   19.0
  12.0   22.0
  12.0   25.0
  14.0   25.0
  14.0   28.0
  16.0   28.0
  18.0   28.0
  18.0   31.0
  18.0   32.0
  18.0   33.0
  21.0   33.0
  21.0   36.0
  21.0   37.0
  21.0   38.0
  23.0   38.0

In [24]:
duplicate_times = (
    pbp.groupby(["gameid", "period", "clock"])
       .size()
       .reset_index(name="count")
)

print("Total timestamps:", len(duplicate_times))
print("Timestamps with multiple events:",
      (duplicate_times["count"] > 1).sum())

duplicate_times[duplicate_times["count"] > 1].head(20)

Total timestamps: 437101
Timestamps with multiple events: 106492

      gameid  period        clock  count
1   22400001       1  PT00M00.40S      2
3   22400001       1  PT00M26.30S      4
10  22400001       1  PT01M38.00S      2
12  22400001       1  PT01M54.00S      2
13  22400001       1  PT01M58.00S      2
14  22400001       1  PT02M19.00S      2
18  22400001       1  PT02M54.00S      4
23  22400001       1  PT03M44.00S      3
29  22400001       1  PT04M27.00S      2
30  22400001       1  PT04M39.00S      3
31  22400001       1  PT04M51.00S      4
33  22400001       1  PT05M27.00S      2
36  22400001       1  PT05M57.00S      7
38  22400001       1  PT06M19.00S      2
39  22400001       1  PT06M20.00S      2
44  22400001       1  PT07M02.00S      4
49  22400001       1  PT07M36.00S      5
62  22400001       1  PT08M46.00S      2
66  22400001       1  PT09M11.00S      4
74  22400001       1  PT10M24.00S      5

In [25]:
pbp[
    (pbp["gameid"] == 52400111) &
    (pbp["period"] == 1) &
    (pbp["clock"] == "PT10M49.00S")
][
    ["gameid", "period", "clock", "team", "type", "h_pts", "a_pts", "desc"]
]

,gameid,period,clock,team,type,h_pts,a_pts,desc
10,52400111,1,PT10M49.00S,CHI,Made Shot,2.0,4.0,White Driving Reverse Layup (2 PTS)
11,52400111,1,PT10M49.00S,MIA,Foul,NaN,NaN,Ware S.FOUL (P1.T1) (J.Van Duyne)
12,52400111,1,PT10M49.00S,CHI,Free Throw,3.0,4.0,White Free Throw 1 of 1 (3 PTS)

In [29]:
def clock_to_seconds(clock):
    if pd.isna(clock):
        return np.nan
    
    clock = str(clock).replace("PT", "").replace("S", "")
    
    if "M" in clock:
        minutes, seconds = clock.split("M")
        return float(minutes) * 60 + float(seconds)
    
    return float(clock)


pbp["clock_seconds"] = pbp["clock"].apply(clock_to_seconds)

# Regulation periods are 12 minutes.
# This creates seconds remaining in the game.
pbp["game_seconds_remaining"] = np.where(
    pbp["period"] <= 4,
    (4 - pbp["period"]) * 720 + pbp["clock_seconds"],
    pbp["clock_seconds"]
)

print(
    pbp[
        ["gameid", "period", "clock",
         "clock_seconds", "game_seconds_remaining"]
    ].head(20)
)

      gameid  period        clock  clock_seconds  game_seconds_remaining
0   52400111       1  PT12M00.00S          720.0                  2880.0
1   52400111       1  PT12M00.00S          720.0                  2880.0
2   52400111       1  PT11M45.00S          705.0                  2865.0
3   52400111       1  PT11M45.00S          705.0                  2865.0
4   52400111       1  PT11M45.00S          705.0                  2865.0
5   52400111       1  PT11M36.00S          696.0                  2856.0
6   52400111       1  PT11M36.00S          696.0                  2856.0
7   52400111       1  PT11M12.00S          672.0                  2832.0
8   52400111       1  PT11M08.00S          668.0                  2828.0
9   52400111       1  PT11M02.00S          662.0                  2822.0
10  52400111       1  PT10M49.00S          649.0                  2809.0
11  52400111       1  PT10M49.00S          649.0                  2809.0
12  52400111       1  PT10M49.00S          649.0                  2809.0
13  52400111       1  PT10M38.00S          638.0                  2798.0
14  52400111       1  PT10M27.00S          627.0                  2787.0
15  52400111       1  PT10M25.00S          625.0                  2785.0
16  52400111       1  PT10M23.00S          623.0                  2783.0
17  52400111       1  PT10M13.00S          613.0                  2773.0
18  52400111       1  PT10M01.00S          601.0                  2761.0
19  52400111       1  PT09M59.00S          599.0                  2759.0

In [30]:
pbp = pbp.sort_values(
    ["gameid", "period", "clock_seconds"],
    ascending=[True, True, False]
).copy()

# Carry the most recent known score forward
pbp["h_pts"] = (
    pbp.groupby("gameid")["h_pts"]
       .ffill()
       .fillna(0)
)

pbp["a_pts"] = (
    pbp.groupby("gameid")["a_pts"]
       .ffill()
       .fillna(0)
)

# Current score differential
pbp["score_diff"] = pbp["h_pts"] - pbp["a_pts"]

print(
    pbp[
        ["gameid", "period", "clock",
         "h_pts", "a_pts", "score_diff"]
    ].head(30)
)

        gameid  period        clock  h_pts  a_pts  score_diff
3014  22400001       1  PT12M00.00S    0.0    0.0         0.0
3015  22400001       1  PT12M00.00S    0.0    0.0         0.0
3016  22400001       1  PT11M43.00S    0.0    0.0         0.0
3017  22400001       1  PT11M43.00S    0.0    0.0         0.0
3018  22400001       1  PT11M42.00S    0.0    0.0         0.0
3019  22400001       1  PT11M38.00S    0.0    0.0         0.0
3020  22400001       1  PT11M37.00S    0.0    0.0         0.0
3021  22400001       1  PT11M24.00S    0.0    0.0         0.0
3022  22400001       1  PT11M22.00S    0.0    0.0         0.0
3023  22400001       1  PT11M17.00S    0.0    0.0         0.0
3024  22400001       1  PT10M57.00S    0.0    0.0         0.0
3025  22400001       1  PT10M57.00S    0.0    0.0         0.0
3026  22400001       1  PT10M55.00S    0.0    0.0         0.0
3027  22400001       1  PT10M55.00S    0.0    0.0         0.0
3028  22400001       1  PT10M54.00S    0.0    0.0         0.0
3029  22400001       1  PT10M54.00S    0.0    0.0         0.0
3030  22400001       1  PT10M50.00S    0.0    3.0        -3.0
3031  22400001       1  PT10M35.00S    3.0    3.0         0.0
3032  22400001       1  PT10M24.00S    3.0    3.0         0.0
3033  22400001       1  PT10M24.00S    3.0    3.0         0.0
3034  22400001       1  PT10M24.00S    3.0    3.0         0.0
3035  22400001       1  PT10M24.00S    3.0    3.0         0.0
3036  22400001       1  PT10M24.00S    3.0    3.0         0.0
3037  22400001       1  PT10M06.00S    3.0    3.0         0.0
3038  22400001       1  PT10M04.00S    3.0    3.0         0.0
3039  22400001       1  PT09M47.00S    3.0    3.0         0.0
3040  22400001       1  PT09M45.00S    3.0    3.0         0.0
3041  22400001       1  PT09M44.00S    3.0    5.0        -2.0
3042  22400001       1  PT09M35.00S    5.0    5.0         0.0
3043  22400001       1  PT09M23.00S    5.0    7.0        -2.0

In [31]:
pbp[
    (pbp["gameid"] == 52400111) &
    (pbp["period"] == 1) &
    (pbp["clock"] == "PT10M49.00S")
][
    ["clock", "team", "type",
     "h_pts", "a_pts", "score_diff"]
]

          clock team        type  h_pts  a_pts  score_diff
10  PT10M49.00S  CHI   Made Shot    2.0    4.0        -2.0
11  PT10M49.00S  MIA        Foul    2.0    4.0        -2.0
12  PT10M49.00S  CHI  Free Throw    3.0    4.0        -1.0

In [32]:

test_game = pbp[pbp["gameid"] == 52400111].copy()

score_states = (
    test_game
    .sort_values("game_seconds_remaining", ascending=False)
    .drop_duplicates(
        subset=["period", "game_seconds_remaining"],
        keep="last"
    )
    [["gameid", "period", "game_seconds_remaining", "score_diff"]]
    .sort_values("game_seconds_remaining", ascending=False)
    .copy()
)

print(score_states.head(20))

      gameid  period  game_seconds_remaining  score_diff
1   52400111       1                  2880.0         0.0
4   52400111       1                  2865.0         0.0
6   52400111       1                  2856.0        -2.0
7   52400111       1                  2832.0        -2.0
8   52400111       1                  2828.0        -2.0
9   52400111       1                  2822.0        -4.0
12  52400111       1                  2809.0        -1.0
13  52400111       1                  2798.0        -3.0
14  52400111       1                  2787.0        -3.0
15  52400111       1                  2785.0        -3.0
16  52400111       1                  2783.0        -1.0
17  52400111       1                  2773.0        -3.0
18  52400111       1                  2761.0        -3.0
19  52400111       1                  2759.0        -3.0
21  52400111       1                  2748.0        -5.0
22  52400111       1                  2738.0        -5.0
23  52400111       1                  2735.0        -5.0
24  52400111       1                  2726.0        -5.0
25  52400111       1                  2723.0        -5.0
27  52400111       1                  2715.0        -5.0

In [33]:

current = score_states[
    ["gameid", "game_seconds_remaining", "score_diff"]
].copy()

current["target_time"] = current["game_seconds_remaining"] + 120

history = score_states[
    ["gameid", "game_seconds_remaining", "score_diff"]
].copy()

history = history.rename(
    columns={
        "game_seconds_remaining": "past_time",
        "score_diff": "past_score_diff"
    }
)

current = current.sort_values(
    ["gameid", "target_time"]
)

history = history.sort_values(
    ["gameid", "past_time"]
)

current = pd.merge_asof(
    current,
    history,
    left_on="target_time",
    right_on="past_time",
    by="gameid",
    direction="backward"
)

current["scoring_diff_2min"] = (
    current["score_diff"] -
    current["past_score_diff"]
)

print(
    current[
        [
            "gameid",
            "game_seconds_remaining",
            "score_diff",
            "past_score_diff",
            "scoring_diff_2min"
        ]
    ].head(20)
)

      gameid  game_seconds_remaining  score_diff  past_score_diff  \
0   52400111                     0.0       -19.0            -21.0
1   52400111                    15.5       -19.0            -21.0
2   52400111                    17.4       -19.0            -21.0
3   52400111                    21.1       -19.0            -21.0
4   52400111                    27.0       -19.0            -21.0
5   52400111                    28.5       -19.0            -21.0
6   52400111                    49.0       -19.0            -21.0
7   52400111                    57.9       -21.0            -21.0
8   52400111                    75.0       -21.0            -21.0
9   52400111                    81.0       -23.0            -21.0
10  52400111                    83.0       -23.0            -21.0
11  52400111                   102.0       -23.0            -23.0
12  52400111                   107.0       -23.0            -23.0
13  52400111                   118.0       -21.0            -23.0
14  52400111                   120.0       -21.0            -23.0
15  52400111                   140.0       -21.0            -23.0
16  52400111                   142.0       -21.0            -23.0
17  52400111                   149.0       -21.0            -23.0
18  52400111                   159.0       -19.0            -20.0
19  52400111                   165.0       -21.0            -20.0

    scoring_diff_2min
0                 2.0
1                 2.0
2                 2.0
3                 2.0
4                 2.0
5                 2.0
6                 2.0
7                 0.0
8                 0.0
9                -2.0
10               -2.0
11                0.0
12                0.0
13                2.0
14                2.0
15                2.0
16                2.0
17                2.0
18                1.0
19               -1.0

## Possession Tracking (Paused)

Possession is one of the most important factors in basketball because teams cannot score without controlling the ball.

The original model does not know which team currently has possession, meaning identical game states could receive the same prediction even though one team has an immediate offensive opportunity.

This section develops a possession-tracking feature from play-by-play events and adds it as an input to the model.

In [ ]:
sample_game = df[df["gameid"] == df["gameid"].iloc[0]].copy()

sample_game = sample_game.reset_index(drop=True)

sample_game.head()

,gameid,period,clock,h_pts,a_pts,team,playerid,player,type,subtype,result,x,y,dist,desc,season
0,20000001,1,PT12M00.00S,0.0,0.0,NaN,0,NaN,period,start,NaN,0,0,0,Start of 1st Period (12:13 PM EST),2001
1,20000001,1,PT12M00.00S,0.0,0.0,NYK,948,M. Camby,Jump Ball,NaN,NaN,0,0,0,Jump Ball Camby vs. Ratliff: Tip to Houston,2001
2,20000001,1,PT11M41.00S,0.0,0.0,NYK,84,L. Sprewell,Missed Shot,Jump Shot,Missed,-58,28,6,MISS Sprewell 6' Jump Shot,2001
3,20000001,1,PT11M41.00S,0.0,0.0,PHI,689,T. Ratliff,NaN,NaN,NaN,0,0,0,Ratliff BLOCK (1 BLK),2001
4,20000001,1,PT11M40.00S,0.0,0.0,NaN,1610612755,NaN,Rebound,Unknown,NaN,0,0,0,76ers Rebound,2001

In [ ]:
teams = sample_game["team"].dropna().unique()

print(teams)

<ArrowStringArray>
['NYK', 'PHI']
Length: 2, dtype: str

In [ ]:
def other_team(current_team, teams):
    if current_team == teams[0]:
        return teams[1]
    else:
        return teams[0]

In [ ]:
sample_game["possession"] = None

In [ ]:
current_possession = None
last_shot_team = None

In [ ]:
current_possession = None

for idx, row in sample_game.iterrows():

    event = row["type"]
    team = row["team"]
    desc = str(row["desc"])


    if event == "Jump Ball":
        current_possession = team


    elif event == "Made Shot":

        last_shot_team = team

        current_possession = other_team(team, teams)


    elif event == "Missed Shot":

        last_shot_team = team


    elif event == "Turnover":
        current_possession = other_team(team, teams)


    elif event == "Rebound":

        rebound_team = None

        if pd.notna(team):
            rebound_team = team

        else:
            desc_lower = desc.lower()

            if "76ers" in desc_lower:
                rebound_team = "PHI"

            elif "knicks" in desc_lower:
                rebound_team = "NYK"

        if rebound_team is not None and last_shot_team is not None:

        
            if rebound_team != last_shot_team:
                current_possession = rebound_team

            else:
                pass


    last_shot_team = None

    sample_game.at[idx, "possession"] = current_possession

In [ ]:
sample_game[
    [
        "clock",
        "team",
        "type",
        "desc",
        "possession"
    ]
].head(40)

,clock,team,type,desc,possession
0,PT12M00.00S,NaN,period,Start of 1st Period (12:13 PM EST),None
1,PT12M00.00S,NYK,Jump Ball,Jump Ball Camby vs. Ratliff: Tip to Houston,NYK
2,PT11M41.00S,NYK,Missed Shot,MISS Sprewell 6' Jump Shot,NYK
3,PT11M41.00S,PHI,NaN,Ratliff BLOCK (1 BLK),NYK
4,PT11M40.00S,NaN,Rebound,76ers Rebound,NYK
5,PT11M29.00S,NYK,Foul,Camby S.FOUL (P1.T1),NYK
6,PT11M29.00S,PHI,Free Throw,Ratliff Free Throw 1 of 2 (1 PTS),NYK
7,PT11M29.00S,PHI,Free Throw,MISS Ratliff Free Throw 2 of 2,NYK
8,PT11M28.00S,NYK,Rebound,Ward REBOUND (Off:0 Def:1),NYK
9,PT11M18.00S,PHI,Foul,Ratliff S.FOUL (P1.T1),NYK
10,PT11M18.00S,NYK,Free Throw,Camby Free Throw 1 of 2 (1 PTS),NYK
11,PT11M18.00S,NYK,Free Throw,Camby Free Throw 2 of 2 (2 PTS),NYK
12,PT11M08.00S,PHI,Missed Shot,MISS Iverson 20' Jump Shot,NYK
13,PT11M06.00S,NYK,Rebound,Camby REBOUND (Off:0 Def:1),NYK
14,PT10M53.00S,NYK,Missed Shot,MISS Houston 15' Jump Shot,NYK
15,PT10M50.00S,NYK,Rebound,Ward REBOUND (Off:1 Def:1),NYK
16,PT10M49.00S,NYK,Turnover,Ward Bad Pass Turnover (P1.T1),PHI
17,PT10M35.00S,PHI,Missed Shot,MISS Hill 10' Jump Shot,PHI
18,PT10M34.00S,NYK,Rebound,Sprewell REBOUND (Off:0 Def:1),PHI
19,PT10M19.00S,NYK,Missed Shot,MISS Sprewell 14' Jump Shot,PHI
20,PT10M18.00S,PHI,Rebound,Lynch REBOUND (Off:0 Def:1),PHI
21,PT10M08.00S,PHI,Made Shot,Ratliff Layup (3 PTS) (Lynch 1 AST),NYK
22,PT09M50.00S,NYK,Made Shot,Houston 16' Jump Shot (2 PTS) (Ward 1 AST),PHI
23,PT09M32.00S,PHI,Turnover,Ratliff Traveling Turnover (P1.T1),NYK
24,PT09M25.00S,PHI,Foul,Snow P.FOUL (P1.T2),NYK
25,PT09M13.00S,NYK,Missed Shot,MISS Johnson Layup,NYK
26,PT09M13.00S,PHI,NaN,Hill BLOCK (1 BLK),NYK
27,PT09M11.00S,NaN,Rebound,76ers Rebound,NYK
28,PT09M11.00S,NYK,Foul,Johnson L.B.FOUL (P1.T2),NYK
29,PT08M56.00S,PHI,Made Shot,Ratliff Slam Dunk (5 PTS) (Lynch 2 AST),NYK
30,PT08M44.00S,NYK,Missed Shot,MISS Camby 17' Jump Shot,NYK
31,PT08M42.00S,PHI,Rebound,Iverson REBOUND (Off:0 Def:1),NYK
32,PT08M31.00S,PHI,Made Shot,Snow Driving Layup (2 PTS) (Iverson 1 AST),NYK
33,PT08M16.00S,NYK,Made Shot,Houston 24' 3PT Jump Shot (5 PTS) (Johnson 1 AST),PHI
34,PT07M57.00S,PHI,Made Shot,Iverson 21' Jump Shot (2 PTS) (Snow 1 AST),NYK
35,PT07M40.00S,NYK,Made Shot,Houston 17' Jump Shot (7 PTS),PHI
36,PT07M23.00S,PHI,Missed Shot,MISS Iverson 17' Jump Shot,PHI
37,PT07M22.00S,PHI,Rebound,Snow REBOUND (Off:1 Def:0),PHI
38,PT07M18.00S,NaN,Timeout,76ers Timeout: Regular (Reg.1 Short 0),PHI
39,PT07M12.00S,NYK,Foul,Ward S.FOUL (P1.T3),PHI

In [ ]:
sample_game.columns.tolist()

['gameid',
 'period',
 'clock',
 'h_pts',
 'a_pts',
 'team',
 'playerid',
 'player',
 'type',
 'subtype',
 'result',
 'x',
 'y',
 'dist',
 'desc',
 'season',
 'possession']

## Model Performance Comparison

After adding possession, the updated feature set is used to train a new Random Forest model.

Performance is compared against the Version 1 model using:

- Accuracy
- Confusion matrix
- Feature importance
- Brier score
- Probability calibration

The goal is to determine whether additional basketball context improves both prediction accuracy and probability reliability.